### ISSUE TITLE
Mergify research

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1008]
**Author the user story for this feature**

As a Flank developer, I want to automatically merge pull requests so I can have less work in progress.

**Additional context**

Setup https://doc.mergify.io/#

**Comment by bootstraponline** [comment]
https://github.com/Flank/flank/commit/fc1f162096ccf167933f1763452e090a32d327df

**Comment by bootstraponline** [comment]
running into this issue: https://github.com/Mergifyio/mergify-engine/issues/722

**Comment by bootstraponline** [comment]
@piotradamczyk5 Maybe you can take a look at this? I'd like to automatically merge Flank pull requests to master once the branch protection settings are met.

**Comment by bootstraponline** [comment]
https://github.com/aws/aws-cdk/blob/master/.mergify.yml has an example configuration used by the AWS CDK project. We might be able to learn something.

**Comment by piotradamczyk5** [comment]
> @piotradamczyk5 Maybe you can take a look at this? I'd like to automatically merge Flank pull requests to master once the branch protection settings are met.

Yeah I could take a look into it

**Comment by piotradamczyk5** [comment]
Hey @bootstraponline 
I have checked configuration and [documentation](https://doc.mergify.io/examples.html#automatic-merge-when-ci-works-and-approving-reviews) and I think that your config is enough because mergify works correctly with GitHub protected branch rules 👍 

```
If you are already using the GitHub Branch Protection system. You can just use:

pull_request_rules:
  - name: automatic merge when GitHub branch protection passes on master
    conditions:
      - base=master
    actions:
      merge:
        method: merge
```

**Comment by piotradamczyk5** [comment]
I would just consider adding options:
```
merge:
  strict: true
  strict_method: rebase
  method: squash
```
For making rebase before the merge as described [here](https://doc.mergify.io/merge-action.html)
