### ISSUE TITLE
Support for Robo Tests without Robo script

### ISSUE THREAD

**Issue by ccjernigan** [Flank/flank#1084]
**Author the user story for this feature**
As an app developer, I want to run robo tests without a robo script so I can sanity check my app before closing a pull request.  

**Is your feature request related to a problem? Please describe.**
I already run instrumentation tests but need a full integration test of the release build.

I need to verify that release builds of my app won't crash immediately on launch since release builds are different.  

Google Play prelaunch reports have caught a variety of obfuscator triggered issues, and they don't require a robo script.  A robo script is not necessary for this (and is difficult for me to implement since my resource names are also obfuscated as part of my build process.)

**Describe the solution you'd like**
Allow Flank to run with just an APK.  Currently Flank says "One of following options must be specified [test, robo-directives, robo-script]."

**Describe alternatives you've considered**
I can do this with `gcloud` directly, so this is a Flank limitation.

I tried supplying fake robo-directives to Flank, but it still gave me the error message "One of following options must be specified [test, robo-directives, robo-script]."

**Comment by pawelpasterz** [comment]
Currently flank enables to run both robo and instrumentation test in parallel, to achieve that we need to pass `robo-script` in the 'main' test pair and test apk as `additional-app-test-apks`
```yml
# this will launch robo test and instrumentation tests for each app in additional-app-test-apks

gcloud:
  app: app-debug.apk
  robo-script: MainActivity.json
flank:
  additional-app-test-apks:
    - test: app-multiple-error-debug-androidTest_1.apk
    - test: app-multiple-error-debug-androidTest_2.apk
```

It is also possible to not specify `test:` 
```yml
# this will only instrumentation tests for each app in additional-app-test-apks, no robo test this time

gcloud:
  app: app-debug.apk
flank:
  additional-app-test-apks:
    - test: app-multiple-error-debug-androidTest_1.apk
    - test: app-multiple-error-debug-androidTest_2.apk
```

Enabling robo tests without `robo-directives` will launch always a simple (let's call it sanity) robo test in the second case.
That will be something that the user would not be aware of and not necessarily like it. On the other hand that is the default behavior of gcloud:
```yml
# this will launch sanity robo

gcloud:
  app: app-debug.apk
```

#### I can see 4 options:
1. remove the feature to launch both robo and instrumentation in parallel (nah...)
2. add option something like `with-sanity-check: true` and that will include sanity robo to the current run (2x nah...)
3. add sanity robo every time `test: null` (I think not user friendly) 
4. run sanity robo ONLY when there is NO, `robo-directives`, `test`, `additional-app-test-apks` (that would reflect gcloud's behavior)

IMO 4) looks nice but I'd like to get your opinion

@bootstraponline @Sloox @adamfilipow92 @piotradamczyk5 @axelzuziak-gogo @jan-gogo
