### ISSUE TITLE
Flank dump shards is inconsistent with what flank is running

### ISSUE THREAD

**Issue by MatthewTPage** [Flank/flank#1103]
**Describe the bug**
I've been seeing some weird behavior with some tests being ran twice, similar to the issue solved in https://github.com/Flank/flank/pull/1048 but on a much smaller scale than I described there - I wanted to view the shard dump to see if anything obvious stuck out but when I run it, I get a shard dump containing only 3 test cases - I have over 2,000 test cases in my suit and flank finds them and runs those properly when I don't tell it to shard dump, so it seems there's an inconsistency between what shard dump outputs and what Flank actually runs.

This issue seems new - v20.09.1 has this issue for me, but v20.08.3 seems to show the proper shards as I expect.

**To Reproduce**
1. Run shard dump on a large test suit.
2. See that it only shows a small number of tests.

**Expected behavior**
It shows the tests in my suit.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?

Yes.

> Post the output of ` flank --version`.

I'm using fladle, but I've been working off of the latest snapshot.

**Additional context**
If it matters I'm using fladle, but because the fladle version can remain constant and I can see it work or not work by changing the flank version, this seems like an issue with flank.

Here are my flank configs (with APK paths removed): https://gist.github.com/MatthewTPage/a356791c742483e211777202403405c4

```yaml
gcloud:
  device:
  - model: Nexus7
    version: 22
    locale: en_US

  use-orchestrator: true
  auto-google-login: false
  record-video: false
  performance-metrics: false
  timeout: 40m
  results-bucket: # A valid bucket name
  num-flaky-test-attempts: 0

flank:
  max-test-shards: 50
  shard-time: 120
  smart-flank-gcs-path: # a valid gs path
  project: api-project-516222937551
  keep-file-path: false
  run-timeout: 45m
  ignore-failed-tests: false
  disable-sharding: false
  smart-flank-disable-upload: false
  legacy-junit-result: true
  full-junit-result: false
  output-style: single
```
