### ISSUE TITLE
CostReport.txt calculates with physical device for NexusLowRes

### ISSUE THREAD

**Issue by hasan-selman-kara-leshop** [Flank/flank#1135]
**Describe the bug**
I'm using device model NexusLowRes API 28, yet the CostReport.txt is:
```
CostReport
  Physical devices
    $9.25 for 1h 51m
```

Also the FetchArtifacts seem to be wrong. Here you can clearly see that the test device is "NexusLowRes" yet the cost report shows physical device.
```
FetchArtifacts
  .................................................
  Updating matrix file

CostReport
  Physical devices
    $10.00 for 2h 0m

  Uploading CostReport.txt .
MatrixResultsReport
  0 / 1 (0.00%)
  1 matrices failed

┌─────────┬──────────────────────┬────────────────────────────┬─────────────────────────────────┐
│ OUTCOME │      MATRIX ID       │      TEST AXIS VALUE       │          TEST DETAILS           │
├─────────┼──────────────────────┼────────────────────────────┼─────────────────────────────────┤
│ failure │ matrix-1x51e23wd43q3 │ NexusLowRes-28-en-portrait │ 17 test cases failed, 32 passed │
└─────────┴──────────────────────┴────────────────────────────┴─────────────────────────────────┘
More details are available at:
https://console.firebase.google.com/project/xyz-apps/testlab/histories/YY/matrices/XX

  Uploading MatrixResultsReport.txt .
  Uploading HtmlErrorReport.html .
```

**To Reproduce**
My flank.yml

```yaml
gcloud:
  test-targets:
    - class com.xyz.LoadTest
  record-video: true
  timeout: 30m
  async: false
  project: xyz-apps
  results-history-name: xyz-name
  app: ../app/build/outputs/apk/integration/debug/app-integration-debug.apk
  test: ../app/build/outputs/apk/androidTest/integration/debug/app-integration-debug-androidTest.apk
  auto-google-login: true
  use-orchestrator: true
  environment-variables:
    clearPackageData: true
  directories-to-pull:
    - /sdcard/screenshots
  performance-metrics: true
  device:
    - model: NexusLowRes
      version: 28
flank:
  # set to -1 to use one shard per test.
  testShards: -1
  repeatTests: 1
```

**Expected behavior**

According to [AndroidCatalogTest.java#L41 ](https://github.com/Flank/flank/blob/master/test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt#L41)this "NexusLowRes" is a virtual device.

Just like in the Android Catalog described:
![image](https://user-images.githubusercontent.com/63003160/93767556-7d4f8700-fc18-11ea-8d12-c23b0c4a3290.png)

Furthermore, in the Firebase Console on the cost break-down the costs don't match what is calculated by flank.

**Details:**

I'm also using the latest flank version
```sh
echo "Building INT app APK and test APK"
./gradlew assembleIntegrationDebug assembleIntegrationDebugAndroidTest

pushd cicd || exit

if [ ! -f flank.jar ]; then
  echo "Downloading the latest flank jar..."
  wget --quiet https://github.com/TestArmada/flank/releases/download/flank_snapshot/flank.jar -O ./flank.jar
fi

echo "Running flank"
java -jar flank.jar firebase test android run
popd || exit

exit 0
```

```sh
java -version
openjdk version "1.8.0_265"
```
