### ISSUE TITLE
gcloud test-targets flag can match multiple classes even if only one is configured

### ISSUE THREAD

**Issue by hasan-selman-kara-leshop** [Flank/flank#1227]
**Describe the bug**
> A clear and concise description of what the bug is.

If you have a package with the following files:
- com.xyz.MyTest1.kt
- com.xyz.MyTest2.kt
- com.xyz.MyTest3.kt
- com.xyz.MyTest10.kt
- com.xyz.MyTest11.kt
- com.xyz.MyTest12.kt
- com.xyz.MyTest13.kt

And configure the flank yaml as follows:
```yml
gcloud:
  test-targets:
    - class com.xyz.MyTest1
```

Flank will match the following test classes: MyTest1; MyTest10; MyTest11; MyTest12; MyTest13

And — let's say each test class has one test method — flank will print the following output

```
Uploading app.apk ....
Uploading app-androidTest.apk .
5 tests / 1 shard
```

**To Reproduce**
1. Create the test files as described above, each with one test method

My flank.yml

```yml
gcloud:
  test-targets:
    - class com.xyz.MyTest1
  record-video: true
  timeout: 60m
  async: false
  app: ./app.apk
  test: ./app-androidTest.apk
  auto-google-login: true
  use-orchestrator: true
  environment-variables:
    clearPackageData: true
  directories-to-pull:
    - /sdcard/screenshots
  performance-metrics: true
  device:
    - model: NexusLowRes
      version: 28
flank:
  testShards: 1
  ignore-failed-tests: true
  repeatTests: 1
```

**Expected behavior**
It should only run the tests of the specified class.

**Details (please complete the following information):**

Flank version 20.09.3
