### ISSUE TITLE
Parameterized classes are always appended to test run

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1234]
**Describe the bug**
> A clear and concise description of what the bug is.

Parameterized classes are always appended to the list of test methods to run

**To Reproduce**
> Steps to reproduce the behavior:

1. Create test apk with at least 3 classes -- `A`,`B` and `C`
1. `C` is a parameterized class
1. Start flank fun with config :
    ```
    gcloud:
      app: ~/app-debug.apk
      test: ~/app-multiple-success-debug-androidTest.apk
      test-targets:
        - class foo.bar.A
    ```
1. Tests from parameterized class are added to list of tests to run

**Expected behavior**
> A clear and concise description of what you expected to happen.

Only tests from `A` should be launched

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

Current snapshot

**Additional context**
> Add any other context about the problem here.
