### ISSUE TITLE
Make the flank output smaller

### ISSUE THREAD

**Issue by arlindiDev** [Flank/flank#1306]
**Author the user story for this feature**

As a developer I want to reduce the output of flank with `outputStyle` 

**Describe the solution**
I want to get rid of the outputs that show:
- Actual shard times
- The executions status per test

**Describe alternatives considered**
So the output should just have, the flank config output, the web matrices links, and the MatrixResultsReport(the nice square), also cost repots

**Comment by adamfilipow92** [comment]
This my proposition for smaller output.

So we remove upload information, execution status we could also remove the second/first weblink.

WDYT?
@bootstraponline @pawelpasterz @jan-gogo @piotradamczyk5 @Sloox @axelzuziak-gogo 

```
AndroidArgs
    gcloud:
      results-bucket: test-lab-v9cn46bb990nx-kz69ymd4nm9aq
      results-dir: 2020-12-02_12-55-30.295558_hSbx
      record-video: false
      timeout: 15m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # Android gcloud
      app: /Users/adamfilipowicz/Repos/flank/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
      test: /Users/adamfilipowicz/Repos/flank/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-success-debug-androidTest.apk
      additional-apks: 
      auto-google-login: false
      use-orchestrator: true
      directories-to-pull: 
      grant-permissions: all
      type: null
      other-files: 
      scenario-numbers: 
      scenario-labels: 
      obb-files: 
      obb-names: 
      performance-metrics: false
      num-uniform-shards: null
      test-runner-class: null
      test-targets:
      robo-directives:
      robo-script: null
      device: 
        - model: NexusLowRes
          version: 28
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0
      test-targets-for-shard: 

    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: 
      smart-flank-disable-upload: false
      default-test-time: 120.0
      use-average-test-time-for-new-tests: false
      files-to-download:
      test-targets-always-run:
      disable-sharding: true
      project: flank-open-source
      local-result-dir: results
      full-junit-result: false
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:
      run-timeout: -1
      legacy-junit-result: false
      ignore-failed-tests: false
      output-style: compact
      disable-results-upload: false
      default-class-test-time: 240.0

RunTests
  1 test / 1 shard

  1 matrix ids created in 0m 17s
  https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-12-02_12-55-30.295558_hSbx

Matrices webLink
  matrix-3lwuvx0exyk67 https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/7713417442968172421/executions/bs.2bec7b7624271cd8

  3m  3s matrix-3lwuvx0exyk67 FINISHED

CostReport
  Virtual devices
    $0.02 for 1m

MatrixResultsReport
  1 / 1 (100.00%)
┌─────────┬──────────────────────┬────────────────────────────┬────────────────────────────────┐
│ OUTCOME │      MATRIX ID       │      TEST AXIS VALUE       │          TEST DETAILS          │
├─────────┼──────────────────────┼────────────────────────────┼────────────────────────────────┤
│ success │ matrix-3lwuvx0exyk67 │ NexusLowRes-28-en-portrait │ 1 test cases passed, 1 skipped │
└─────────┴──────────────────────┴────────────────────────────┴────────────────────────────────┘
FetchArtifacts
  .
  Updating matrix file


Matrices webLink
  matrix-3lwuvx0exyk67 https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/7713417442968172421/executions/bs.2bec7b7624271cd8


Process finished with exit code 0
```
