### ISSUE TITLE
IOS GCloud, Flank command parity

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1341]
This is a perfectly valid gcloud command:
```
gcloud alpha firebase test ios run 
--type game-loop --app build/ipa/flankgameloop.ipa --scenario-numbers 1 
--device model=iphone11,version=13.6
```

This is not:
```
gcloud:
  app: test_projects/ios/FlankGameLoopExample/ipa/FlankGameLoopExample.ipa
  type: game-loop
  scenario-numbers:
      - 1
  device:
      - model: iphone11
        version: 13.6
        orientation: portrait
        locale: en_US
```

Flank expects a xctestrunfile & test, as it fails the above command with:
`Both of following options must be specified [test, xctestrun-file].`

is this necessary?

some changes would be needed to get it to parity.
