### ISSUE TITLE
Output inconsistency (ios vs android)

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1388]
**Describe the bug**
> A clear and concise description of what the bug is.

There are differences in flank output for iOS and Android when all test are filtered
Below is the output for https://github.com/Flank/flank/blob/master/integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
* iOS https://gist.github.com/pawelpasterz/e517272563a0bcbf83fb4fdbcf94d549
* android https://gist.github.com/pawelpasterz/5a4d8498629b716abd86cd0b70ee4b2e

**To Reproduce**
> Steps to reproduce the behavior:

1. run ios test with config 
    ```
    gcloud:
      test: [path to zip]
      xctestrun-file: [path to xctestrun]
    flank:
      test-targets:
        - nonExisting/Class
    ```
1. run android test with config 
    ```
    gcloud:
      app: [path to app apk]
      test: [path to test apk]
      test-targets:
        - class non.existing.Class
    flank:
      disable-sharding: true
    ```

**Expected behavior**
> A clear and concise description of what you expected to happen.

There is a decision to be made if flank should (or not) print args.
Based on the answer:
* fix should be implemented
* IT must be updated

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
version: local_snapshot
revision: 2d2982474e9d38ee39639ed7282b84fb5e33ce01
```

**Additional context**
> Add any other context about the problem here.

Introduced in https://github.com/Flank/flank/pull/1219
