### ISSUE TITLE
Different exit codes iOS vs android

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1389]
**Describe the bug**
> A clear and concise description of what the bug is.

When all tests are filtered android run ends with exit code 1 when ios with 2.

**To Reproduce**
> Steps to reproduce the behavior:

1. run ios test with config 
    ```
    gcloud:
      test: [path to zip]
      xctestrun-file: [path to xctestrun]
    flank:
      test-targets:
        - nonExisting/Class
    ```
1. run android test with config 
    ```
    gcloud:
      app: [path to app apk]
      test: [path to test apk]
      test-targets:
        - class non.existing.Class
    flank:
      disable-sharding: true
    ```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Exit code should be the same for both, ios and android. Need to decide which one to use.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
version: local_snapshot
revision: 2d2982474e9d38ee39639ed7282b84fb5e33ce01
```

**Additional context**
> Add any other context about the problem here.

https://firebase.google.com/docs/test-lab/android/command-line#script_exit_codes
