### ISSUE TITLE
Fails with "Instrumentation tests require a valid test-runner-class defined." after upgrading to v21.01.0

### ISSUE THREAD

**Issue by kubode** [Flank/flank#1444]
**Describe the bug**
> A clear and concise description of what the bug is.

I got `Instrumentation tests require a valid test-runner-class defined.` error when I run `flank run android` after upgrading to `v21.01.0`:

[The documentation](https://flank.github.io/flank/#android-example) says: 

> ```
>   ### Instrumentation Test Runner Class
>   ## The fully-qualified Java class name of the instrumentation test runner
>   ## (default: the last name extracted from the APK manifest).
>   # test-runner-class: com.foo.TestRunner
> ```

`test-runner-class` is not required but, I got the error.
Is the documentation is wrong?

**To Reproduce**
> Steps to reproduce the behavior:

1. Set `gcloud.type: instrumentation` to your `flank.yml`.
2. Run `flank run android`.
3. Flank exits with `Instrumentation tests require a valid test-runner-class defined.` error.

**Expected behavior**
> A clear and concise description of what you expected to happen.

No errors.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
version: v21.01.0
revision: 66cff410ff585beffba5f150799b3f77b7065dfb
```

My `flank.yml`:
```yml
gcloud:
  type: instrumentation
  app: # [REDACTED]
  test: # [REDACTED]
  device:
    - model: walleye
      version: 28
      locale: en_US
      orientation: portrait
  environment-variables:
    timeout_msec: 20000
    coverage: true
    coverageFile: /sdcard/coverage.ec
    clearPackageData: true
  use-orchestrator: false
  directories-to-pull:
    - /sdcard/
  timeout: 10m

flank:
  max-test-shards: 8
  shard-time: 50
  smart-flank-gcs-path: # [REDACTED]
  test-targets-always-run:
    - class # [REDACTED]
  files-to-download:
    - .*/sdcard/[^/]+\.ec$
```

**Additional context**
> Add any other context about the problem here.

This issue did not happen with `v20.09.3`.
Seems like this issue was included at https://github.com/Flank/flank/pull/1230.
