### ISSUE TITLE
Invalid value for [project] and failed to make bucket

### ISSUE THREAD

**Issue by CityTransit** [Flank/flank#1792]
**Describe the bug**
> A clear and concise description of what the bug is.

I believe that Flank may be having trouble with our legacy project-id. Our project is very old and our Firebase ID is of the format `company.com:appname`. Does it seem as if Flank might not like our project ID as it contains a colon and a dot? 

I've tried with the project number as well which gives the same error.

**To Reproduce**
> Steps to reproduce the behavior:

Running `$ flank android run` gives

```
version: v21.04.0
revision: eb4ee0c932f609d843ab5353445876aa1273e332
session id: c6f4d030-12d9-4354-991f-66bc975edc08

Warning: Failed to make a bucket for 59732999025
Cause: You already own this bucket. Please select another name.

Invalid value for [project]: no argument value found
```

with flank.yml:

```
gcloud:
  results-bucket: "flank"
  timeout: "30m"
  app: "app/build/outputs/apk/stagingEspresso/debug/App-staging-espresso-debug.apk"
  test: "app/build/outputs/apk/androidTest/stagingEspresso/debug/App-staging-espresso-debug-androidTest.apk"
  device:
  - model: "NexusLowRes"
    version: "28"
    locale: "en"
    orientation: "portrait"
flank:
  project: "59732999025" # or "company.com:appname"
```

(the first time it was run, or if I delete the bucket, the warning does not appear)

**Expected behavior**
> A clear and concise description of what you expected to happen.

I expect the tests to run, or to provide output that helps to solve the issue.
Also, I've noticed in the [documentation](https://flank.github.io/flank/) yaml samples are references to "project name". This undoubtedly should be changed to project id, correct?

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
version: v21.04.0
revision: eb4ee0c932f609d843ab5353445876aa1273e332
session id: c6f4d030-12d9-4354-991f-66bc975edc08
```
