### ISSUE TITLE
Corellium MVP

### ISSUE THREAD

**Issue by zuziakaxel** [Flank/flank#1798]
# Corellium Android Tests MVP

## Goal

The goal is to :
* implement sharding, which allows to:
    * split test cases from one test apk to run on many devices.
    * group test cases from many test apks to run on a single device.
    * mix both of the above options.
* run tests on Corellium android devices.
* deliver all above as library module dependency for flank.

#### Constraints

* One `execution` can invoke many `devices` for testing
* One `device` can be used for testing many `app apks`
* One `app apk` can have associated many `test apks`

#### Keywords

* `execution` - a single run of the `$ flank corellium test android run`.
* `device` - an abstraction for the device provided by Corellium through VPN+ADB or API.
* `app apk` - `apk` file with application.
* `test apk` - `apk` file with tests.

#### Diagram

![cli-domain-sequence](http://www.plantuml.com/plantuml/png/lPDDJiCm48NtFiMeh7C1X51B-H4IAtuEOEAX7J4U1tjSkk3mnAGG9L8Yf29sbVtcwvldbsLI6pLxDizX3uicOa9HgnG4AbZVtIxWX6cprGlEQ9fMIpKrLXHMuc8WjmuHcIdx-ophuBqLPr0Sj3ZJCLtmbWfDGmECE-Hlvar4b06qXJnYqZ5xYiZX_OTetxBrDf8CRTQMwynMyM5heqk3kvZb4dTKu_2O9AbbNZMl8tbdBlLkZ9bE0QhpoNKcpil8oE-azAognbeuXUx7dAioDyKyVluG9torYcGpjscV_koIlQpbFmafVC3LliQcTFIFdA8RG6TCzzsOTzth_its4Qz-U2tGKk_VHX6xg_aS3g8ImdNvMii_5FEQZsXPHtmXeRGTPM2MA2vx_WG0)

#### Auto sharding:

```yaml
corellium:
  test-apks:
    - app: /path/to/app1.apk
      tests:
        - apk: /path/to/app-android-test1.apk
    - app: /path/to/app2.apk
      tests:
        - apk: /path/to/app-android-test1.apk
        - apk: /path/to/app-android-test2.apk
```

#### Manual sharding:

```yaml
corellium:
  test-apks:
    - app: /path/to/app.apk
      tests:
        - apk: /path/to/app-android-test1.apk
          shards:
            - shard-0:
                - "class com.TestClassA#test1"
                - "class com.TestClassA#test2"
                - "class com.package2.TestClassB#test4"
            - shard-1:
                - "class com.TestClassA#test3"
                - "class com.package2.TestClassB#test1"
                - "class com.package2.TestClassB#test2"
                - "class com.package2.TestClassB#test3"
        - apk: /path/to/app-android-test2.apk
          shards:
            - shard-0:
                - "class com.ParameterizedTest"
                - "class com.package3.TestClass3#test5"
            - shard-1:
                - "class com.package3.TestClass3#test1"
                - "class com.package3.TestClass3#test2"
            - shard-2:
                - "class com.package3.TestClass3#test3"
                - "class com.package3.TestClass3#test4"
```

### Output

The standard `JUnitReport.xml`
