### ISSUE TITLE
iPhone 11 Pro not recognized as correct device 

### ISSUE THREAD

**Issue by mariuszmachniakzendesk** [Flank/flank#2179]
**Describe the bug**
> I setup Flank to use iPhone 11 Pro on Firebase. The tests are executing properly however at the end it doesn't recognize the device properly in cost calculations and matrix fetching.

This is the output from Flank when running in Github Actions build:
`Unable to find device type for iphone11pro. PHYSICAL used as fallback in cost calculations
FetchArtifacts
  Unable to find device type for iphone11pro. PHYSICAL used as fallback in cost calculations
  Updating matrix file
CostReport
  No cost. 0m
`

**To Reproduce**
1. Setup flank.ios.yml to use iPhone 11 Pro iOS 14.7
```
device:
  - model: iphone11pro
    version: 14.7
    locale: en
    orientation: portrait
```
2. Run tests in Firebase using `java -jar flank.jar firebase test ios run`

**Comment by bootstraponline** [comment]
Thanks for the clear repro steps. I fixed the bug in https://github.com/Flank/flank/pull/2182 and verified the fix works with the settings below.

```
gcloud:
  test: "./test_runner/src/test/kotlin/ftl/fixtures/tmp/ios/EarlGreyExample/EarlGreyExample.zip"
  xctestrun-file: "./test_runner/src/test/kotlin/ftl/fixtures/tmp/ios/EarlGreyExample/EarlGreyExampleSwiftTests.xctestrun"
  device:
  - model: "iphone11pro"
    version: "14.7"
    locale: "en"
    orientation: "portrait"
```

```
CostReport
  Physical devices
    $0.08 for 1m
```
