### ISSUE TITLE
How can I run XCUITest tests in parallel using 4 shards and split the tests with the devices

### ISSUE THREAD

**Issue by moatazeldebsy** [Flank/flank#664]
How can I run `XCUITest` tests in `parallel` using `4 shards` and split the tests with the devices like `Android` because I tried it and it's run the **whole** `scheme` on each device using the following `flank.yml `file:

```
gcloud:
  results-bucket: ta
  results-dir: ios
  record-video: true
  async: false
  timeout: 45m
  num-flaky-test-attempts: 1
  test: $TEST_BUNDLE_ZIP_PATH
  xctestrun-file: $XCTESTRUN_FILE_PATH
  xcode-version: 10.3
  device:
    - model: iphonexsmax
      version: 12.3
      locale: en
      orientation: portrait
flank:
  max-test-shards: 4
  shard-time: -1
  num-test-runs: 1
```
