### ISSUE TITLE
Additional Test Apks does not support wildcards

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#732]
we can specify app and test targets with wildcards like so:
```
gcloud:
      app: app/build/outputs/apk/debug/*.apk
      test: app/build/outputs/apk/androidTest/debug/*.apk
flank:
additional-app-test-apks:
        - app: app/build/outputs/apk/debug/*.apk
          test: app/build/outputs/apk/androidTest/debug/*.apk
```

But additional test apks does not support wildcards and will fail with a NoSuchFileException
