### ISSUE TITLE
OOM - Process killed by CI when fetching artifacts

### ISSUE THREAD

**Issue by doodla** [Flank/flank#758]
![image](https://user-images.githubusercontent.com/3683106/80752652-b3149780-8ae0-11ea-9ba8-426b638012a4.png)

When running the FetchArtifacts step, the process is occasionally killed by CircleCI. I think it's possibly because the files are not being streamed to disk, but are held in memory first.

**Comment by jan-gogo** [comment]
There must be another reason. Flank doesn't hold file artifacts in memory, it uses [`downloadTo`](https://github.com/Flank/flank/blob/f8e1b021dd9a2c5a0e8673c499d628799d6bbad2/test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt#L47) function from class `com.google.cloud.storage.Blob` which [under the hood](https://github.com/googleapis/java-storage/blob/32d8fface1a994cb5ac928f08c0467edc3c9aab1/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java#L231) writes gclouds `Blobs` to files directly via `OutputStream`

**Comment by bootstraponline** [comment]
I've used `Files.readAllBytes(data)` throughout the codebase, maybe that should change? Doodla is running on low memory VMs.

**Comment by jan-gogo** [comment]
> I've used `Files.readAllBytes(data)` throughout the codebase, maybe that should change? Doodla is running on low memory VMs.

Right that could be a problem. I will try to fix that.

**Comment by jan-gogo** [comment]
@doodla Could you share your yaml config and version of flank? It could be helpful.

**Comment by bootstraponline** [comment]
I think we could probably replicate this on a very low memory linux virtual machine.

**Comment by doodla** [comment]
```
AndroidArgs
    gcloud:
      results-bucket: ***********-flank
      results-dir: null
      record-video: false
      timeout: 8m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # Android gcloud
      app: /opt/workspace/scripts/app-us-prod-debug.apk
      test: /opt/workspace/scripts/app-us-prod-debug-androidTest.apk
      additional-apks: 
      auto-google-login: false
      use-orchestrator: true
      directories-to-pull:
      other-files:
      performance-metrics: false
      num-uniform-shards: null
      test-runner-class: null
      test-targets:
        - annotation com.creditkarma.testing.ui.EspressoTest
      robo-directives:
      robo-script: null
      device:
        - model: Nexus4
          version: 21
          locale: en
          orientation: portrait
        - model: Nexus5
          version: 22
          locale: en
          orientation: portrait
        - model: Nexus7_clone_16_9
          version: 23
          locale: en
          orientation: portrait
        - model: Nexus5X
          version: 24
          locale: en
          orientation: portrait
        - model: Nexus5X
          version: 25
          locale: en
          orientation: portrait
        - model: NexusLowRes
          version: 26
          locale: en
          orientation: portrait
        - model: Nexus6P
          version: 27
          locale: en
          orientation: portrait
        - model: Pixel2
          version: 28
          locale: en
          orientation: portrait
        - model: Pixel2
          version: 29
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 2

    flank:
      max-test-shards: 15
      shard-time: 100
      num-test-runs: 1
      smart-flank-gcs-path: gs://***********-android/test_timings.xml
      smart-flank-disable-upload: false
      files-to-download:
      test-targets-always-run:
      disable-sharding: false
      project: ***********
      local-result-dir: test-lab-results
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:
      run-timeout: -1
      legacy-junit-result: false
      ignore-failed-tests: false
```

Here's my config @jan-gogo . I used to be on a 1CPU 2GB ram circle VM where I saw issues. We're now on a 2CPU 4GB ram machine. [Basically went from small to medium](https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes).
