### ISSUE TITLE
Don't set TestTargets when disable-sharding: true and test-targets is missing

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#815]
**Describe the bug**

Users set `disable-sharding: true` when Flank is unable to discover tests via bytecode parsing. Flank should not set test targets at all when disable sharding is enabled if no test targets are specified. This allows Firebase Test Lab to dynamically discover the tests at runtime.

**To Reproduce**

Run flank with:

```
gcloud:
  app: ./app/build/outputs/apk/singleSuccess/debug/app-single-success-debug.apk
  test: ./app/build/outputs/apk/androidTest/singleSuccess/debug/app-single-success-debug-androidTest.apk
  use-orchestrator: false

flank:
  disable-sharding: true
```

Check the matrix on FTL and see that test targets are specified.
![image](https://user-images.githubusercontent.com/1173057/82768477-29f13780-9de4-11ea-8709-4374d612b3c6.png)

**Expected behavior**

Test targets should not be specified when disable sharding is true and test-targets is not set.

![image](https://user-images.githubusercontent.com/1173057/82768714-97ea2e80-9de5-11ea-8a16-1276681a493c.png)

**Details (please complete the following information):**

```
$ flank --version
version: local_snapshot
revision: f23c7b7099aa30f2670220cce475e1a0e434c908
```

**Additional context**

See https://github.com/Flank/flank/pull/786 for an example use case (cucumber).
