### ISSUE TITLE
Shards failed - no test cases inside

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#818]
> Mr.uno 
>
> One or more shards failed because there are no test cases inside. Please check your sharding configuration. I've encountered this a couple times with our submodule tests which use a lot of additional test apks. Maybe some error somewhere in that logic - I've only ever seen it with the submodule tests. This is from the latest Flank version.

![image](https://user-images.githubusercontent.com/1173057/83044337-e4f21e80-9ff8-11ea-908a-b742f0431ab8.png)

https://firebase-community.slack.com/archives/C72V6UW8M/p1590537597298100

**Comment by inktomi** [comment]
Thank you for getting this filed for me! I'm not feeling well today, but I wanted to provide our config as well. 

We build a dummy app for the `app` - it's basically just the app you get from the "New Application" template in Android Studio. 

```yaml
flank:
  additional-app-test-apks:
  - test: feature/1/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/2/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/3/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/4/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/5/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/6/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/7/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/8/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/9/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/10/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/11/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/12/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/13/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/14/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/15/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/16/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/17/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/18/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/19/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/20/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/21/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/22/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/23/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/24/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/25/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/26/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/27/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  legacy-junit-result: 'false'
  local-result-dir: sub-modules-flank-results
  max-test-shards: 5
  project: project-id-12345
  run-timeout: 20m
  smart-flank-gcs-path: gs://project-id-12345-flank/submodules-timing.xml
gcloud:
  app: ./sample-app/build/outputs/apk/debug/sample-app-tester-debug.apk
  async: false
  auto-google-login: false
  device:
  - model: NexusLowRes
    version: 23
  environment-variables:
    clearPackageData: true
  performance-metrics: false
  record-video: false
  results-bucket: sub-modules-flank-results
  test: feature/28/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  test-targets:
  - notAnnotation org.junit.Ignore
  use-orchestrator: true
```

I was getting an error like this before I added the `notAnnotation` to ensure that Ignored tests were not causing issues. After I added that, it seemed like maybe a bucket consisted entirely of ignored tests or something like that and I started getting the error in the original report here about a shard having no tests. I only noticed ` One or more shards failed because there are no test cases inside. Please check your sharding configuration.` in the Firebase UI after adding the test filter but the error seemed to happen in both cases since the stacktrace is consistent. 

```
 java.lang.ClassNotFoundException: Invalid name: no tests found
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
at com.americanexpress.android.test.view.ViewTestRunner.onStart(ViewTestRunner.kt:25)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879) 
```
