### ISSUE TITLE
Print environment variables

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#834]
**Describe the bug**
When `environment-variables` was set flank won't print it to output. 

**To Reproduce**
1. Minimum yml file to reproduce
```
gcloud:
  app: ./src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
  robo-script: ./src/test/kotlin/ftl/fixtures/test_app_cases/MainActivity_robo_script.json
  environment-variables:
    coverage: true
    coverageFilePath: /sdcard/
    clearPackageData: true


```
2. Run flank with this yml
3. See Android args output
```
AndroidArgs
    gcloud:
      results-bucket: test-lab-v9cn46bb990nx-kz69ymd4nm9aq
      results-dir: 2020-06-03_14-54-35.991299_fSGl
      record-video: false
      timeout: 15m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # Android gcloud
      app: /Users/adamfilipowicz/Repos/flank/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
      test: null
      additional-apks: 
      auto-google-login: false
      use-orchestrator: true
      directories-to-pull:
      other-files:
      performance-metrics: false
      num-uniform-shards: null
      test-runner-class: null
      test-targets:
      robo-directives:
      robo-script: /Users/adamfilipowicz/Repos/flank/test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/MainActivity_robo_script.json
      device:
        - model: NexusLowRes
          version: 28
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0

    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: 
      smart-flank-disable-upload: false
      files-to-download:
      test-targets-always-run:
      disable-sharding: false
      project: flank-open-source
      local-result-dir: results
      full-junit-result: true
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:
      run-timeout: -1
      legacy-junit-result: false
      ignore-failed-tests: false
      output-style: single
(...)
```
**Expected behavior**
Probably flank should print environment variables. 

Tell me what do you think.
@bootstraponline @jan-gogo @pawelpasterz @piotradamczyk5
