### ISSUE TITLE
Tests are included in XCTest entries that do not contain the test

### ISSUE THREAD

**Issue by RainNapper** [Flank/flank#842]
**Describe the bug**
If the original xctestrun has multiple XCTest entries, Tests included via `--test-targets` flag will be added to the `OnlyTestIdentifiers` array on every XCTest entry, not just the one(s) that actually includes that test.

**To Reproduce**
Start with a xctestrun that has multiple xctests:
e.g.
```
<plist version="1.0">
<dict>
	<key>TestSuiteA</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteA.xctest</string>
        </dict>
	<key>TestSuiteB</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteB.xctest</string>
        </dict>
</dict>
```

and run flank over that xctestrun with `--test-targets` for a test within only one of those suites, e.g. `ClassB/methodC` as a part of SuiteA

**Expected behavior**
Flank should produce main_shard_0.xctestrun that contains:
```
<plist version="1.0">
<dict>
	<key>TestSuiteA</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteA.xctest</string>
		<key>OnlyTestIdentifiers</key>
		<array>
			<string>ClassB/methodC</string>
		</array>
        </dict>
</dict>
```

**Details (please complete the following information):**
Flank produces main_shard_0.xctestrun instead that contains:
```
<plist version="1.0">
<dict>
	<key>TestSuiteA</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteA.xctest</string>
		<key>OnlyTestIdentifiers</key>
		<array>
			<string>ClassB/methodC</string>
		</array>
        </dict>
	<key>TestSuiteB</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteB.xctest</string>
		<key>OnlyTestIdentifiers</key>
		<array>
			<string>ClassB/methodC</string>
		</array>
        </dict>
</dict>
```

Version:
```
$ java -jar tools/flank/flank-v20.05.2.jar --version
version: v20.05.2
revision: 7618ebdb5a74db4b448de0b93357221de3ab10c2
```

.yml config:
```
gcloud:
  record-video: true
  timeout: 10m
  async: false
  # iOS gcloud
  test: FirebasePayload.zip
  xctestrun-file: FirebasePayload/main.xctestrun
  xcode-version: 11.3.1
  device:
    - model: iphone8
      version: 12.0
      locale: en
  results-history-name: ios-flank
flank:
  max-test-shards: 50
  num-test-runs: 1
```
