### ISSUE TITLE
Ability to configure job to test on a physical device

### ISSUE THREAD

**Issue by liangmicha** [Flank/flank#861]
I am not sure whether this feature is already built. 

I want to kick off a job in firebase test lab for a physical devise, here is the device section of my `flank.yml` that leads to test run virtually (in an emulator):
```
  device:
  - model: Pixel2
    version: 26
    locale: en
    orientation: portrait
```
I added a `form: physical` argument but that doesn't work and I'm having trouble finding documentation on this. Does anyone know if running on a physical device is supported with flank? If so, how do I configure it?
