### ISSUE TITLE
Flank Doctor doesn't catch invalid yaml

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#911]
With the following yaml:
```
gcloud:
  app: /Users/no/workspace/fladle/sample/build/outputs/apk/debug/sample-debug.apk
  test: /Users/no/workspace/fladle/sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk
  device:
  - model: Nexus5
    version: 23
  use-orchestrator: true
  auto-google-login: false
  record-video: true
  performance-metrics: true
  timeout: 15m
  environment-variables:
    clearPackageData: true
  test-targets:
  - class com.osacky.flank.gradle.sample.ExampleInstrumentedTest#seeView
  num-flaky-test-attempts: 1
flank:
  additional-app-test-apks:
    app: ../main/app/build/output/apk/debug/app.apk
    test: ../main/app/build/output/apk/androidTest/debug/app-test.apk
    app: ../sample/app/build/output/apk/debug/sample-app.apk
    test: ../sample/app/build/output/apk/androidTest/debug/sample-app-test.apk
    test: ../feature/room/build/output/apk/androidTest/debug/feature-room-test.apk
    test: ../library/databases/build/output/apk/androidTest/debug/sample-databases-test.apk
```
running `firebase test android doctor`
yields:
```
version: v20.07.0
revision: 02bca2797b2d6c1ce4bba95a12428d5a49cc8f63

Valid yml file
```
However running: `firebase test android run`
yields
```
version: v20.07.0
revision: 02bca2797b2d6c1ce4bba95a12428d5a49cc8f63

Error on parse config: flank->additional-app-test-apks
At line: 24, column: 5
Error node: {
  "smart-flank-gcs-path" : "gs://test-lab-yr9w6qsdvy45q-iurp80dm95h8a/flank/test_app_android.xml",
  "keep-file-path" : false,
  "additional-app-test-apks" : {
    "app" : "../sample/app/build/output/apk/debug/sample-app.apk",
    "test" : "../library/databases/build/output/apk/androidTest/debug/sample-databases-test.apk"
  },
  "ignore-failed-tests" : false,
  "disable-sharding" : false,
  "smart-flank-disable-upload" : false,
  "output-style" : "single"
}
```
