### ISSUE TITLE
error invoking ios flank with gcloud 

### ISSUE THREAD

**Issue by westdorp** [Flank/flank#997]
**Describe the bug**
> A clear and concise description of what the bug is.

I followed the steps laid out in Flank's read me to configure using flank on circleci. The step to deploy to run tests with Firebase Test Lab keeps failing when trying to run tests using `gcloud alpha firebase test ios run flank.ios.yml:gcloud
`. The error I get is ERROR: (gcloud.alpha.firebase.test.ios.run) Invalid value for [version]: 12.0

**To Reproduce**
> Steps to reproduce the behavior:

1. Run 'gcloud alpha firebase test ios run flank.ios.yml:gcloud'
2. See error (gcloud.alpha.firebase.test.ios.run) Invalid value for [version]: 12.0

**Expected behavior**
> A clear and concise description of what you expected to happen.

Tests should be deployed to Firebase Test Lab or an error description that can be better understood

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
> Yes
> Post the output of ` flank --version`.

version: v20.08.1
revision: e9ed26c8f2fdc77fca9f0e436558d89f7f99ef17

**Additional context**
> Add any other context about the problem here.

I have also tried running `flank ios run` and the result I get is `null`. I'm including the yml file parsing that was printed when running the method
```
version: v20.08.1
revision: e9ed26c8f2fdc77fca9f0e436558d89f7f99ef17
IosArgs
    gcloud:
      results-bucket: cloud-test-${GOOGLE_PROJECT_ID}
      results-dir: circleci-${CIRCLE_BUILD_NUM}
      record-video: true
      timeout: 15m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # iOS gcloud
      test: /Users/distiller/project/fastlane/test_output/build_products.zip
      xctestrun-file: /Users/distiller/project/UITest_iphonesimulator13.4-x86_64.xctestrun
      xcode-version: null
      device:
        - model: iphone8
          version: 12.0
          locale: en
          orientation: portrait
        - model: iphonexr
          version: 13.2
          locale: en
          orientation: portrait
        - model: iphonese
          version: 11.4
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0
    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: gs://tmp_flank/flank/test_app_ios.xml
      smart-flank-disable-upload: false
      test-targets-always-run:
      files-to-download:
      keep-file-path: false
      full-junit-result: false
      # iOS flank
      test-targets:
      disable-sharding: false
      project: turnstyle-8663d
      local-result-dir: results
      run-timeout: -1
      ignore-failed-tests: false
      output-style: multi
RunTests
  Uploading build_products.zip ..
null
```
